apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: testapp
    repo: someurlchart
    version: "12.10.1"
    releaseName: testapp
    namespace: fundament
    valuesFile: helm-values/testapp.yaml

resources:
  - manifests
