apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager-webhook-transip
    repo: https://demeester.dev/cert-manager-webhook-transip
    version: "0.1.4"
    releaseName: cert-manager-webhook-transip
    namespace: cert-manager
    valuesFile: helm-values/cert-manager-webhook-transip.yaml

resources:
  - manifests
