apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fundament-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: fundament-ca
  secretName: fundament-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
