apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-options
  namespace: istio-system
data:
  deployment: |
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      gateway.networking.k8s.io/gateway-name: gateway
                  topologyKey: kubernetes.io/hostname
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
