apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-test-cluster
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  bootstrap:
    initdb:
      database: pgtestdb
      owner: my-test-db-owner
      # secret:
      #   name: my-test-db-secret # This tells operator to USE an existing secret, not CREATE it

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  storage:
    size: 1Gi
